# Generated by Django 4.2 on 2023-05-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfid',
            name='sent_from_server',
            field=models.BooleanField(default=True),
        ),
    ]
